[build]
builder = "nixpacks"
# Define the full build process here, including dependency installation
buildCommand = "python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"

[build.nixpacks]
pkgs = ["python38", "gcc"]  # Python 3.8 and gcc for building dependencies

[deploy]
startCommand = "uvicorn omi_trans:app --host 0.0.0.0 --port $PORT"