[build]
builder = "nixpacks"
buildCommand = "pip install --no-cache-dir -r requirements.txt"

nixpacksPlan = """
  [phases.setup]
  nixPkgs = ['python39', 'gcc'] # Use Python 3.9 if needed

  [phases.build]
  cmds = ['pip install --no-cache-dir -r requirements.txt']

  [phases.install]
  cmds = ['echo "Dependencies installed successfully"']

  [start]
  cmd = "uvicorn omi_trans:app --host 0.0.0.0 --port ${PORT:-8000}"
"""
